# Generated by Django 3.0.4 on 2020-07-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('temperature', models.FloatField()),
                ('condition', models.TextField()),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
